services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: localuser
      POSTGRES_DB: localdb
      POSTGRES_PASSWORD: localpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
